version: "2"
services:
  piac-backend:
    image: piac-backend
    build: .
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/piac-dev
      populateWithDemoData: "true"
      my.sendgrid.apikey: $SENDGRID_API_KEY
      sendgrid.from-email: $SENDGRID_FROM_EMAIL
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/authentication.cnf:/etc/mysql/conf.d/authentication.cnf
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: piac-dev
    ports:
      - 3306:3306
