version: '2'
services:

 # spring-boot-skeleton:
  #  image: spring-boot-skeleton:latest
   # build: .
    #restart: always
  #  ports:
   #   - 8081:8081
  #  links:
   #   - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: skeleton
    ports:
      - 3306:3306
