version: "2"
services:
  piac-backend:
    image: piac-backend
    build: .
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/piac-dev
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    platform: x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: piac-dev
    ports:
      - 3306:3306
