name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency: ci-${{ github.event_name	}}-${{ github.ref }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build frontend
    defaults:
      run:
        shell: bash
        working-directory: frontend
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/frontend:${{ github.sha }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run Tests
        run: yarn test

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/backend:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  build-admin:
    name: Build admin
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: admin
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/admin:${{ github.sha }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: admin/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('admin/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run Prettier
        run: npx prettier --check .

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  test-frontend:
    name: Run site tests
    runs-on: ubuntu-latest
    needs: [build-frontend]
    defaults:
      run:
        shell: bash
        working-directory: frontend
    env:
      CYPRESS_BASE_URL: http://site
    services:
      site:
        image: registry.gitlab.com/6uliver/piac/frontend:${{ github.sha }}
        ports: [80]
        credentials:
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run Cypress tests
        run: yarn e2e-test:run

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: frontend/results/**/*.xml

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: stage
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: [build-frontend, build-backend, build-admin, test-frontend]
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/felpenzzel
            ./deploy.sh stage ${{ github.sha }}

  deploy-live:
    name: Deploy to live
    runs-on: ubuntu-latest
    environment: live
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build-frontend, build-backend, build-admin, test-frontend]
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/felpenzzel
            ./deploy.sh live ${{ github.sha }}
