name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency: ci-${{ github.event_name	}}-${{ github.ref }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build frontend
    defaults:
      run:
        shell: bash
        working-directory: frontend
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/frontend
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Pull or build deps image
        run: |
          DEP_HASH=$(sha256sum yarn.lock | cut -d " " -f1)
          DEPS_IMAGE_TAG=deps-${DEP_HASH}
          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || echo "deps image not found"
          docker build --target deps --cache-from=$IMAGE_NAME:${DEPS_IMAGE_TAG} -t $IMAGE_NAME:${DEPS_IMAGE_TAG} --build-arg BUILDKIT_INLINE_CACHE=1 .
          docker push $IMAGE_NAME:${DEPS_IMAGE_TAG}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Copy test results
        run: docker build --target test-output --output . .

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Unit test results - frontend
          files: frontend/junit.xml

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.sha }}

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    services:
      db:
        image: mysql:8.0
        ports: ["3306:3306"]
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: piac-test
        volumes:
          - ./backend/mysql/authentication.cnf:/etc/mysql/conf.d/
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/backend
      MYSQL_URL: jdbc:mysql://localhost:3306/piac-test
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: mvn -B test

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Pull or build deps image
        run: |
          DEP_HASH=$(sha256sum pom.xml | cut -d " " -f1)
          DEPS_IMAGE_TAG=deps-${DEP_HASH}
          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || echo "deps image not found"
          docker build --target deps --cache-from=$IMAGE_NAME:${DEPS_IMAGE_TAG} -t $IMAGE_NAME:${DEPS_IMAGE_TAG} --build-arg BUILDKIT_INLINE_CACHE=1 .
          docker push $IMAGE_NAME:${DEPS_IMAGE_TAG}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.sha }}

  build-admin:
    name: Build admin
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: admin
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/admin
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Pull or build deps image
        run: |
          DEP_HASH=$(sha256sum yarn.lock | cut -d " " -f1)
          DEPS_IMAGE_TAG=deps-${DEP_HASH}
          docker pull $IMAGE_NAME:${DEPS_IMAGE_TAG} || echo "deps image not found"
          docker build --target deps --cache-from=$IMAGE_NAME:${DEPS_IMAGE_TAG} -t $IMAGE_NAME:${DEPS_IMAGE_TAG} --build-arg BUILDKIT_INLINE_CACHE=1 .
          docker push $IMAGE_NAME:${DEPS_IMAGE_TAG}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.sha }}

  test-frontend:
    name: Run site tests
    runs-on: ubuntu-latest
    needs: [build-frontend]
    defaults:
      run:
        shell: bash
        working-directory: frontend
    env:
      CYPRESS_BASE_URL: http://site
    services:
      site:
        image: registry.gitlab.com/6uliver/piac/frontend:${{ github.sha }}
        ports: ["80:80"]
        credentials:
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
    container:
      image: cypress/included:9.1.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run Cypress tests
        run: yarn e2e-test:run

      - name: Publish Cypress test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Cypress test results - frontend
          files: frontend/results/**/*.xml

      - name: Archive video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: videos
          path: frontend/cypress/videos

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: frontend/cypress/screenshots

  test-admin:
    name: Run admin tests
    runs-on: ubuntu-latest
    needs: [build-admin]
    defaults:
      run:
        shell: bash
        working-directory: admin
    env:
      CYPRESS_BASE_URL: http://admin
    services:
      admin:
        image: registry.gitlab.com/6uliver/piac/admin:${{ github.sha }}
        ports: ["80:80"]
        credentials:
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
    container:
      image: cypress/included:9.1.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: admin/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('admin/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run Cypress tests
        run: yarn e2e-test:run

      - name: Publish Cypress test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Cypress test results - admin
          files: admin/results/**/*.xml

      - name: Archive video
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: videos
          path: admin/cypress/videos

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: admin/cypress/screenshots

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: stage
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs:
      [build-frontend, build-backend, build-admin, test-frontend, test-admin]
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/felpenzzel
            ./deploy.sh stage ${{ github.sha }}

  deploy-live:
    name: Deploy to live
    runs-on: ubuntu-latest
    environment: live
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      [build-frontend, build-backend, build-admin, test-frontend, test-admin]
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/felpenzzel
            ./deploy.sh live ${{ github.sha }}
