name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build frontend
    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: frontend/coverage/lcov-report

      - name: Build frontend
        run: npm run build

      - name: Archive frontend bundle
        uses: actions/upload-artifact@v2
        with:
          name: piac-frontend
          path: frontend/build

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    env:
      IMAGE_NAME: registry.gitlab.com/6uliver/piac/backend:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME
